version: '2.0'

services:

  #------------------------------------------------------------------
  # Volumes
  #------------------------------------------------------------------


  #------------------------------------------------------------------
  # Containers App
  #------------------------------------------------------------------

  nginx:
    container_name: test_birdie_nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      testbirdie:
        ipv4_address: 18.1.22.2
    volumes:
      - ./:/mnt/app
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    container_name: test_birdie_php_fpm
    image: mcmakler/docker-php7-fpm
    restart: unless-stopped
    networks:
      testbirdie:
        ipv4_address: 18.1.22.3
    volumes:
      - ./:/mnt/app

  php-fpm-seed:
    container_name: test_birdie_php_fpm_seed
    image: composer
    command: composer install --ignore-platform-reqs --no-scripts
    volumes:
      - ./:/app

  redis:
    container_name: test_birdie_redis
    image: redis:3.2
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      testbirdie:
        ipv4_address: 18.1.22.4

  mongodb:
    container_name: test_birdie_mongodb
    image: mongo:3.4
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      testbirdie:
        ipv4_address: 18.1.22.5

  mongodb-seed:
    container_name: test_birdie_mongodb_seed
    image: mongo:3.4
    networks:
      testbirdie:
        ipv4_address: 18.1.22.6
    command: mongoimport --host mongodb --db birdie --collection country --type json --file /country.json --jsonArray
    volumes:
      - ./data/country.json:/country.json

networks:
  testbirdie:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 18.1.22.0/16
